#!/usr/bin/env python3
"""Append batch-2 demo cases (009-012 per scenario) to demo_cases.json."""

from __future__ import annotations

import json
from pathlib import Path

FIXTURES = Path(__file__).resolve().parents[1] / "fixtures"
CASES_PATH = FIXTURES / "demo_cases.json"

BATCH_2: list[dict] = [
    {
        "id": "fraud-009",
        "scenario": "telecom_fraud",
        "tags": ["high_risk", "rich_slots"],
        "difficulty": "medium",
        "input": "有人自称公安局说我涉嫌洗钱，让我把生活费转到安全账户，银行卡刚转了8000",
        "expected_risk": "high",
        "expected_next_action": "handoff_human",
        "expected_emotion": "fearful",
        "expected_completeness": 0.75,
        "expected_slots": {
            "fraud_method": "冒充公检法",
            "loss_amount": 8000,
            "transfer_channel": "银行卡",
            "still_contacting": True
        },
        "expected_missing_fields": ["evidence"],
        "expected_high_risk_flags": ["still_contacting"],
        "expected_next_question": "请不要再转账。是否还有对方电话、网址或聊天记录？",
        "expected_next_question_keywords": ["不要", "转账", "记录"],
        "evaluator_notes": "冒充公检法经典话术；金额大，宜转人工。",
    },
    {
        "id": "fraud-010",
        "scenario": "telecom_fraud",
        "tags": ["rich_slots", "emotion_heavy"],
        "difficulty": "medium",
        "input": "网恋对象让我帮她买游戏点卡，两个月累计转了6000多，现在她把我删了",
        "expected_risk": "medium",
        "expected_next_action": "ask_followup",
        "expected_emotion": "anxious",
        "expected_completeness": 0.5,
        "expected_slots": {
            "fraud_method": "网恋交友诈骗",
            "loss_amount": 6000,
            "still_contacting": False
        },
        "expected_missing_fields": ["transfer_channel", "evidence"],
        "expected_high_risk_flags": [],
        "expected_next_question": "主要是通过什么方式转账的？有没有聊天和转账截图？",
        "expected_next_question_keywords": ["转账", "截图"],
        "evaluator_notes": "杀猪盘/交友诈骗变体。",
    },
    {
        "id": "fraud-011",
        "scenario": "telecom_fraud",
        "tags": ["boundary", "high_risk"],
        "difficulty": "hard",
        "input": "之前被骗3000，刚有人自称平台客服说能退款，让我先交2000保证金",
        "expected_risk": "high",
        "expected_next_action": "handoff_human",
        "expected_emotion": "urgent",
        "expected_completeness": 0.5,
        "expected_slots": {
            "fraud_method": "二次退款诈骗",
            "loss_amount": 2000,
            "still_transferring": True
        },
        "expected_missing_fields": ["transfer_channel", "evidence"],
        "expected_high_risk_flags": ["still_transferring"],
        "expected_next_question": "请立即停止向所谓客服转账。对方如何联系你的？",
        "expected_next_question_keywords": ["停止", "客服"],
        "acceptable_alternate_scenarios": ["telecom_fraud"],
        "boundary_notes": "二次诈骗；仍属 telecom_fraud。",
        "evaluator_notes": "退款代办类二次诈骗。",
    },
    {
        "id": "fraud-012",
        "scenario": "telecom_fraud",
        "tags": ["rich_slots"],
        "difficulty": "easy",
        "input": "收到短信说欠费要点击链接充值，充了50块话费才发现不对",
        "expected_risk": "low",
        "expected_next_action": "ask_followup",
        "expected_emotion": "neutral",
        "expected_completeness": 0.5,
        "expected_slots": {
            "fraud_method": "钓鱼短信充值",
            "loss_amount": 50,
            "platform": "短信链接"
        },
        "expected_missing_fields": ["transfer_channel", "evidence"],
        "expected_high_risk_flags": [],
        "expected_next_question": "充值是通过什么渠道完成的？短信和支付截图还在吗？",
        "expected_next_question_keywords": ["渠道", "截图"],
        "evaluator_notes": "小额诈骗，测试低金额路径。",
    },
    {
        "id": "loss-009",
        "scenario": "property_loss",
        "tags": ["rich_slots"],
        "difficulty": "easy",
        "input": "今天上午第三节课在教三楼教室丢了雨伞，黑色折叠伞",
        "expected_risk": "low",
        "expected_next_action": "ask_followup",
        "expected_emotion": "neutral",
        "expected_completeness": 1.0,
        "expected_slots": {
            "lost_item": "雨伞",
            "lost_time": "今天上午第三节课",
            "lost_location": "教三楼教室",
            "item_features": "黑色折叠伞",
            "suspected_theft": False
        },
        "expected_missing_fields": [],
        "expected_high_risk_flags": [],
        "expected_next_question": "下课后是否问过同学或查看教室监控？",
        "expected_next_question_keywords": ["监控", "同学"],
        "evaluator_notes": "低价值纯遗失。",
    },
    {
        "id": "loss-010",
        "scenario": "property_loss",
        "tags": ["rich_slots", "regression"],
        "difficulty": "medium",
        "input": "实验室电脑显示器不见了，昨晚关门时还在，型号戴尔24寸",
        "expected_risk": "medium",
        "expected_next_action": "ask_followup",
        "expected_emotion": "anxious",
        "expected_completeness": 1.0,
        "expected_slots": {
            "lost_item": "电脑显示器",
            "lost_time": "昨晚至今早",
            "lost_location": "实验室",
            "item_features": "戴尔24寸",
            "suspected_theft": True
        },
        "expected_missing_fields": [],
        "expected_high_risk_flags": [],
        "expected_next_question": "实验室是否有门禁记录或监控？是否已报告导师？",
        "expected_next_question_keywords": ["监控", "导师"],
        "evaluator_notes": "实验室资产遗失。",
    },
    {
        "id": "loss-011",
        "scenario": "property_loss",
        "tags": ["boundary"],
        "difficulty": "hard",
        "input": "快递放在宿舍楼下货架被人拆了，里面的耳机没了，顺丰显示已签收",
        "expected_risk": "medium",
        "expected_next_action": "ask_followup",
        "expected_emotion": "angry",
        "expected_completeness": 0.75,
        "expected_slots": {
            "lost_item": "快递内耳机",
            "lost_location": "宿舍楼下快递货架",
            "item_features": "顺丰快递内耳机",
            "suspected_theft": True
        },
        "expected_missing_fields": ["lost_time"],
        "expected_high_risk_flags": [],
        "expected_next_question": "大概什么时候发现被拆的？有没有向快递员或驿站投诉并拍照？",
        "expected_next_question_keywords": ["什么时候", "拍照"],
        "acceptable_alternate_scenarios": ["telecom_fraud"],
        "boundary_notes": "快递被盗属财物遗失，非典型网络诈骗。",
        "evaluator_notes": "快递盗窃/遗失边界。",
    },
    {
        "id": "loss-012",
        "scenario": "property_loss",
        "tags": ["rich_slots"],
        "difficulty": "easy",
        "input": "校园卡丢了，已挂失，昨天在体育馆洗澡间丢的",
        "expected_risk": "low",
        "expected_next_action": "give_guidance",
        "expected_emotion": "neutral",
        "expected_completeness": 1.0,
        "expected_slots": {
            "lost_item": "校园卡",
            "lost_time": "昨天",
            "lost_location": "体育馆洗澡间",
            "item_features": "已挂失",
            "account_or_id_risk": False
        },
        "expected_missing_fields": [],
        "expected_high_risk_flags": [],
        "expected_next_question": "是否需要整理一份遗失经过给保卫处备案？",
        "expected_next_question_keywords": ["保卫处", "备案"],
        "evaluator_notes": "已挂失，风险低，偏指引。",
    },
    {
        "id": "conflict-009",
        "scenario": "dorm_conflict",
        "tags": ["rich_slots"],
        "difficulty": "easy",
        "input": "室友总在阳台抽烟，味道飘进我床位，说了几次还抽",
        "expected_risk": "low",
        "expected_next_action": "ask_followup",
        "expected_emotion": "angry",
        "expected_completeness": 0.5,
        "expected_slots": {
            "parties": "我与室友",
            "conflict_reason": "阳台抽烟影响他人",
            "time_location": "宿舍阳台/床位"
        },
        "expected_missing_fields": ["expected_resolution"],
        "expected_high_risk_flags": [],
        "expected_next_question": "你希望怎么处理？是否需要宿管或辅导员协调？",
        "expected_next_question_keywords": ["怎么处理", "辅导员"],
        "evaluator_notes": "生活习惯类冲突。",
    },
    {
        "id": "conflict-010",
        "scenario": "dorm_conflict",
        "tags": ["rich_slots"],
        "difficulty": "medium",
        "input": "室友经常带校外朋友回宿舍过夜，吵到两三点，我睡眠很差",
        "expected_risk": "medium",
        "expected_next_action": "ask_followup",
        "expected_emotion": "anxious",
        "expected_completeness": 0.75,
        "expected_slots": {
            "parties": "我与室友及校外人员",
            "conflict_reason": "带人过夜噪音大",
            "time_location": "宿舍夜间",
            "frequency": "经常"
        },
        "expected_missing_fields": ["expected_resolution"],
        "expected_high_risk_flags": [],
        "expected_next_question": "你是否已向宿管反映？希望换宿还是限时管理访客？",
        "expected_next_question_keywords": ["宿管", "换宿"],
        "evaluator_notes": "访客管理类宿舍矛盾。",
    },
    {
        "id": "conflict-011",
        "scenario": "dorm_conflict",
        "tags": ["boundary"],
        "difficulty": "medium",
        "input": "舍友在群里骂我人品差，但没说要打我，我现在不想回宿舍",
        "expected_risk": "low",
        "expected_next_action": "ask_followup",
        "expected_emotion": "anxious",
        "expected_completeness": 0.75,
        "expected_slots": {
            "parties": "我与舍友",
            "conflict_reason": "群内辱骂",
            "time_location": "宿舍/微信群",
            "threat": False
        },
        "expected_missing_fields": ["expected_resolution"],
        "expected_high_risk_flags": [],
        "expected_next_question": "你希望学校怎么处理？是否需要辅导员调解或暂时调换宿舍？",
        "expected_next_question_keywords": ["辅导员", "宿舍"],
        "acceptable_alternate_scenarios": ["personal_safety_threat"],
        "boundary_notes": "网络辱骂但未明确威胁，优先宿舍冲突。",
        "evaluator_notes": "与 threat 场景区分：无明确威胁人身。",
    },
    {
        "id": "conflict-012",
        "scenario": "dorm_conflict",
        "tags": ["emotion_heavy", "regression"],
        "difficulty": "medium",
        "input": "找过辅导员调解两次了，室友还是故意摔门针对我，我不知道还能怎么办",
        "expected_risk": "medium",
        "expected_next_action": "ask_followup",
        "expected_emotion": "anxious",
        "expected_completeness": 0.75,
        "expected_slots": {
            "parties": "我与室友",
            "conflict_reason": "故意摔门针对",
            "previous_communication": "辅导员调解两次",
            "frequency": "反复",
            "emotional_intensity": "高"
        },
        "expected_missing_fields": ["time_location"],
        "expected_high_risk_flags": [],
        "expected_next_question": "最近一次大概什么时候发生的？是否考虑正式申请换宿？",
        "expected_next_question_keywords": ["什么时候", "换宿"],
        "evaluator_notes": "已介入调解仍无效，需记录既往处置。",
    },
    {
        "id": "threat-009",
        "scenario": "personal_safety_threat",
        "tags": ["high_risk", "handoff", "rich_slots"],
        "difficulty": "medium",
        "input": "收到陌生号码发来的刀的照片，说知道我在哪个宿舍楼，我很害怕",
        "expected_risk": "high",
        "expected_next_action": "handoff_human",
        "expected_emotion": "fearful",
        "expected_completeness": 0.75,
        "expected_slots": {
            "threat_type": "恐吓信息/武器图片",
            "suspect_info": "陌生号码",
            "current_location": "宿舍区域",
            "danger_level": "高度恐惧",
            "evidence": "刀的照片短信",
            "ongoing_threat": True
        },
        "expected_missing_fields": ["prior_incidents"],
        "expected_high_risk_flags": ["ongoing_threat"],
        "expected_next_question": "请先保存截图并不要回复对方。你现在是否在安全房间？是否已联系保卫处或报警？",
        "expected_next_question_keywords": ["截图", "报警", "安全"],
        "evaluator_notes": "武器图片+掌握位置，高风险。",
    },
    {
        "id": "threat-010",
        "scenario": "personal_safety_threat",
        "tags": ["high_risk", "rich_slots"],
        "difficulty": "medium",
        "input": "昨晚网约车司机知道我宿舍楼栋，今天又在校门口晃，我不敢一个人走",
        "expected_risk": "high",
        "expected_next_action": "handoff_human",
        "expected_emotion": "fearful",
        "expected_completeness": 1.0,
        "expected_slots": {
            "threat_type": "跟踪/尾随",
            "suspect_info": "网约车司机",
            "current_location": "校门口",
            "danger_level": "不敢独自行走",
            "prior_incidents": "昨晚及今日",
            "ongoing_threat": True,
            "current_danger": True
        },
        "expected_missing_fields": [],
        "expected_high_risk_flags": ["ongoing_threat", "current_danger"],
        "expected_next_question": "你现在是否在校门口？能否立即到保卫处或人多的地方并报警？",
        "expected_next_question_keywords": ["保卫", "报警"],
        "evaluator_notes": "校外人员跟踪，反复出现。",
    },
    {
        "id": "threat-011",
        "scenario": "personal_safety_threat",
        "tags": ["boundary", "emotion_heavy"],
        "difficulty": "hard",
        "input": "家里亲戚打电话骂我并说要来学校打我，我现在在宿舍，他还没到",
        "expected_risk": "medium",
        "expected_next_action": "ask_followup",
        "expected_emotion": "fearful",
        "expected_completeness": 1.0,
        "expected_slots": {
            "threat_type": "亲属言语威胁",
            "suspect_info": "家里亲戚",
            "current_location": "宿舍",
            "danger_level": "对方尚未到达但担心",
            "ongoing_threat": False
        },
        "expected_missing_fields": [],
        "expected_high_risk_flags": [],
        "expected_next_question": "是否有具体到达时间或路线？建议告知辅导员/保卫处并保存通话记录，你现在身边有人吗？",
        "expected_next_question_keywords": ["辅导员", "记录", "身边"],
        "acceptable_alternate_scenarios": ["dorm_conflict"],
        "boundary_notes": "亲属冲突；若强调即将到达可升 high。",
        "evaluator_notes": "非室友威胁，仍属人身安全。",
    },
    {
        "id": "threat-012",
        "scenario": "personal_safety_threat",
        "tags": ["boundary", "rich_slots"],
        "difficulty": "medium",
        "input": "实验室同学散布谣言说我作弊，还扬言要在楼下堵我，我今天没去实验室",
        "expected_risk": "medium",
        "expected_next_action": "ask_followup",
        "expected_emotion": "anxious",
        "expected_completeness": 1.0,
        "expected_slots": {
            "threat_type": "谣言+扬言堵人",
            "suspect_info": "实验室同学",
            "current_location": "宿舍（未去实验室）",
            "danger_level": "担心但今日未遭遇",
            "prior_incidents": "散布谣言",
            "ongoing_threat": False
        },
        "expected_missing_fields": [],
        "expected_high_risk_flags": [],
        "expected_next_question": "对方今天是否真的出现在楼下？有没有聊天记录或证人？",
        "expected_next_question_keywords": ["今天", "聊天记录"],
        "acceptable_alternate_scenarios": ["dorm_conflict"],
        "boundary_notes": "校园人际关系冲突含威胁用语；主场景人身威胁。",
        "evaluator_notes": "扬言但未发生，风险 medium。",
    },
]


def main() -> None:
    cases = json.loads(CASES_PATH.read_text(encoding="utf-8"))
    existing_ids = {c["id"] for c in cases}
    added = 0
    for case in BATCH_2:
        if case["id"] not in existing_ids:
            cases.append(case)
            added += 1
    CASES_PATH.write_text(
        json.dumps(cases, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print(f"Total cases: {len(cases)} (added {added})")


if __name__ == "__main__":
    main()
