#!/usr/bin/env python3
"""Append batch-3 demo cases (013-016 per scenario)."""

from __future__ import annotations

import json
from pathlib import Path

CASES_PATH = Path(__file__).resolve().parents[1] / "fixtures" / "demo_cases.json"

BATCH_3: list[dict] = [
    {
        "id": "fraud-013",
        "scenario": "telecom_fraud",
        "tags": ["rich_slots", "regression"],
        "difficulty": "easy",
        "input": "QQ群里领红包链接点进去，让我输银行卡验证码，结果扣了1500",
        "expected_risk": "medium",
        "expected_next_action": "ask_followup",
        "expected_emotion": "anxious",
        "expected_completeness": 0.5,
        "expected_slots": {"fraud_method": "钓鱼链接盗刷", "loss_amount": 1500, "platform": "QQ群"},
        "expected_missing_fields": ["transfer_channel", "evidence"],
        "expected_high_risk_flags": [],
        "expected_next_question": "银行卡是否已挂失？有没有链接截图和扣款短信？",
        "expected_next_question_keywords": ["挂失", "截图"],
        "evaluator_notes": "钓鱼链接/验证码类诈骗。",
    },
    {
        "id": "fraud-014",
        "scenario": "telecom_fraud",
        "tags": ["emotion_heavy"],
        "difficulty": "medium",
        "input": "校园贷平台说我逾期要上门，让我再转3000平账，我慌了",
        "expected_risk": "high",
        "expected_next_action": "handoff_human",
        "expected_emotion": "fearful",
        "expected_completeness": 0.5,
        "expected_slots": {
            "fraud_method": "校园贷恐吓催收",
            "loss_amount": 3000,
            "still_transferring": True,
        },
        "expected_missing_fields": ["transfer_channel", "evidence"],
        "expected_high_risk_flags": ["still_transferring"],
        "expected_next_question": "请先不要继续转账。对方如何联系你？是否已向学校资助中心或警方咨询？",
        "expected_next_question_keywords": ["不要", "转账"],
        "evaluator_notes": "校园贷+恐吓，易诱发继续转账。",
    },
    {
        "id": "fraud-015",
        "scenario": "telecom_fraud",
        "tags": ["boundary", "sparse_input"],
        "difficulty": "hard",
        "input": "免费领游戏皮肤要登录还要短信验证码，我给了",
        "expected_risk": "medium",
        "expected_next_action": "ask_followup",
        "expected_emotion": "neutral",
        "expected_completeness": 0.25,
        "expected_slots": {"fraud_method": "免费福利钓鱼"},
        "expected_missing_fields": ["loss_amount", "transfer_channel", "evidence"],
        "expected_high_risk_flags": [],
        "expected_next_question": "有没有发生扣款或账号被盗？大概损失多少钱或通过什么渠道支付？",
        "expected_next_question_keywords": ["扣款", "多少钱"],
        "evaluator_notes": "可能尚未转账，先判诈骗类钓鱼。",
    },
    {
        "id": "fraud-016",
        "scenario": "telecom_fraud",
        "tags": ["sparse_input", "slang"],
        "difficulty": "medium",
        "input": "刷单的米没了，对方还催我补单",
        "expected_risk": "high",
        "expected_next_action": "handoff_human",
        "expected_emotion": "urgent",
        "expected_completeness": 0.25,
        "expected_slots": {"fraud_method": "刷单诈骗", "still_contacting": True},
        "expected_missing_fields": ["loss_amount", "transfer_channel", "evidence"],
        "expected_high_risk_flags": ["still_contacting"],
        "expected_next_question": "先别继续转账。一共转了多少钱？通过什么方式转的？",
        "expected_next_question_keywords": ["别", "多少钱"],
        "evaluator_notes": "网络用语「米」=钱； slang 测试。",
    },
    {
        "id": "loss-013",
        "scenario": "property_loss",
        "tags": ["rich_slots"],
        "difficulty": "easy",
        "input": "钥匙串丢了，三把钥匙加一个小熊挂件，昨晚在操场跑步",
        "expected_risk": "low",
        "expected_next_action": "ask_followup",
        "expected_emotion": "neutral",
        "expected_completeness": 1.0,
        "expected_slots": {
            "lost_item": "钥匙串",
            "lost_time": "昨晚",
            "lost_location": "操场",
            "item_features": "三把钥匙加小熊挂件",
        },
        "expected_missing_fields": [],
        "expected_high_risk_flags": [],
        "expected_next_question": "操场周边有没有监控或拾物处可以问？",
        "expected_next_question_keywords": ["监控"],
        "evaluator_notes": "低价值遗失。",
    },
    {
        "id": "loss-014",
        "scenario": "property_loss",
        "tags": ["rich_slots"],
        "difficulty": "easy",
        "input": "洗澡间眼镜不见了，黑框近视镜，大概半小时前",
        "expected_risk": "low",
        "expected_next_action": "ask_followup",
        "expected_emotion": "neutral",
        "expected_completeness": 1.0,
        "expected_slots": {
            "lost_item": "眼镜",
            "lost_time": "大概半小时前",
            "lost_location": "洗澡间",
            "item_features": "黑框近视镜",
        },
        "expected_missing_fields": [],
        "expected_high_risk_flags": [],
        "expected_next_question": "是否问过洗澡间管理员或查看附近监控？",
        "expected_next_question_keywords": ["监控"],
        "evaluator_notes": "浴室遗失常见。",
    },
    {
        "id": "loss-015",
        "scenario": "property_loss",
        "tags": ["noise_prefix", "rich_slots"],
        "difficulty": "hard",
        "input": "对了今天食堂人好多啊，哦说正事，我U盘在机房电脑边丢了，32G黑色，下午实验课",
        "expected_risk": "low",
        "expected_next_action": "ask_followup",
        "expected_emotion": "neutral",
        "expected_completeness": 1.0,
        "expected_slots": {
            "lost_item": "U盘",
            "lost_time": "下午实验课",
            "lost_location": "机房",
            "item_features": "32G黑色",
        },
        "expected_missing_fields": [],
        "expected_high_risk_flags": [],
        "expected_next_question": "机房有没有监控或同学坐在旁边？",
        "expected_next_question_keywords": ["监控"],
        "evaluator_notes": "前置闲聊噪声，测试抽取抗干扰。",
    },
    {
        "id": "loss-016",
        "scenario": "property_loss",
        "tags": ["typo", "slang"],
        "difficulty": "medium",
        "input": "俺书包落图书馆了，里面笔记本夹身份证，急死",
        "expected_risk": "high",
        "expected_next_action": "handoff_human",
        "expected_emotion": "urgent",
        "expected_completeness": 0.75,
        "expected_slots": {
            "lost_item": "书包",
            "lost_location": "图书馆",
            "item_features": "内有笔记本和身份证",
            "account_or_id_risk": True,
        },
        "expected_missing_fields": ["lost_time"],
        "expected_high_risk_flags": ["account_or_id_risk"],
        "expected_next_question": "大概什么时候发现落的？身份证有没有去挂失或补办？",
        "expected_next_question_keywords": ["什么时候", "身份证"],
        "evaluator_notes": "方言/错别字；落=丢。",
    },
    {
        "id": "conflict-013",
        "scenario": "dorm_conflict",
        "tags": ["rich_slots"],
        "difficulty": "easy",
        "input": "室友偷用我插排还给弄坏了，也不赔，在宿舍吵了一架",
        "expected_risk": "low",
        "expected_next_action": "ask_followup",
        "expected_emotion": "angry",
        "expected_completeness": 0.75,
        "expected_slots": {
            "parties": "我与室友",
            "conflict_reason": "偷用插排并损坏",
            "time_location": "宿舍",
            "physical_conflict": False,
        },
        "expected_missing_fields": ["expected_resolution"],
        "expected_high_risk_flags": [],
        "expected_next_question": "你希望赔偿还是请宿管调解？",
        "expected_next_question_keywords": ["赔偿", "宿管"],
        "evaluator_notes": "财物+冲突，主场景宿舍。",
    },
    {
        "id": "conflict-014",
        "scenario": "dorm_conflict",
        "tags": ["rich_slots"],
        "difficulty": "medium",
        "input": "室友养仓鼠味道很大，说了也不理，我想举报",
        "expected_risk": "low",
        "expected_next_action": "ask_followup",
        "expected_emotion": "angry",
        "expected_completeness": 0.5,
        "expected_slots": {
            "parties": "我与室友",
            "conflict_reason": "宿舍养宠物异味",
            "expected_resolution": "举报",
        },
        "expected_missing_fields": ["time_location"],
        "expected_high_risk_flags": [],
        "expected_next_question": "这种情况持续多久了？学校是否禁止宿舍养宠物？",
        "expected_next_question_keywords": ["多久"],
        "evaluator_notes": "宠物引发矛盾。",
    },
    {
        "id": "conflict-015",
        "scenario": "dorm_conflict",
        "tags": ["slang", "emotion_heavy"],
        "difficulty": "medium",
        "input": "舍友老针对我，无语死了，天天翻白眼",
        "expected_risk": "low",
        "expected_next_action": "ask_followup",
        "expected_emotion": "angry",
        "expected_completeness": 0.25,
        "expected_slots": {"parties": "我与舍友", "conflict_reason": "针对、冷暴力"},
        "expected_missing_fields": ["time_location", "expected_resolution"],
        "expected_high_risk_flags": [],
        "expected_next_question": "最近一次什么时候发生的？你想换宿舍还是调解？",
        "expected_next_question_keywords": ["什么时候", "换宿舍"],
        "evaluator_notes": "口语/网络用语。",
    },
    {
        "id": "conflict-016",
        "scenario": "dorm_conflict",
        "tags": ["boundary", "multi_topic"],
        "difficulty": "hard",
        "input": "室友偷用我手机转账，我们还吵起来了，他说要揍我",
        "expected_risk": "high",
        "expected_next_action": "handoff_human",
        "expected_emotion": "fearful",
        "expected_completeness": 0.5,
        "expected_slots": {
            "parties": "我与室友",
            "conflict_reason": "偷用手机转账并争吵",
            "threat": True,
        },
        "expected_missing_fields": ["time_location", "expected_resolution"],
        "expected_high_risk_flags": ["threat"],
        "expected_next_question": "手机转账损失多少？对方有没有动手？你现在是否安全？",
        "expected_next_question_keywords": ["转账", "安全"],
        "acceptable_alternate_scenarios": ["telecom_fraud", "personal_safety_threat"],
        "boundary_notes": "含诈骗+威胁；宿舍冲突为主，转账损失需同步记录。",
        "evaluator_notes": "多主题混合案例。",
    },
    {
        "id": "threat-013",
        "scenario": "personal_safety_threat",
        "tags": ["rich_slots"],
        "difficulty": "medium",
        "input": "晚上回宿舍路上总觉得有人在后面跟着，同一外套连三天了",
        "expected_risk": "medium",
        "expected_next_action": "ask_followup",
        "expected_emotion": "fearful",
        "expected_completeness": 1.0,
        "expected_slots": {
            "threat_type": "疑似跟踪",
            "suspect_info": "不明身份，同外套",
            "current_location": "宿舍路上",
            "danger_level": "持续不安",
            "prior_incidents": "连续三天",
        },
        "expected_missing_fields": [],
        "expected_high_risk_flags": [],
        "expected_next_question": "对方今天是否还在？能否描述身高外貌并联系保卫处？",
        "expected_next_question_keywords": ["保卫"],
        "evaluator_notes": "跟踪未确认，中等风险。",
    },
    {
        "id": "threat-014",
        "scenario": "personal_safety_threat",
        "tags": ["high_risk", "rich_slots"],
        "difficulty": "medium",
        "input": "收到邮件说要杀了我，还知道我课表，我在教学楼很害怕",
        "expected_risk": "high",
        "expected_next_action": "handoff_human",
        "expected_emotion": "fearful",
        "expected_completeness": 1.0,
        "expected_slots": {
            "threat_type": "死亡威胁邮件",
            "suspect_info": "发件人不明",
            "current_location": "教学楼",
            "danger_level": "高度恐惧",
            "evidence": "威胁邮件",
            "ongoing_threat": True,
        },
        "expected_missing_fields": [],
        "expected_high_risk_flags": ["ongoing_threat"],
        "expected_next_question": "请先保存邮件原件并到有人处。是否已联系保卫处或报警？",
        "expected_next_question_keywords": ["保卫", "报警"],
        "evaluator_notes": "死亡威胁+掌握行程。",
    },
    {
        "id": "threat-015",
        "scenario": "personal_safety_threat",
        "tags": ["multi_topic", "boundary"],
        "difficulty": "hard",
        "input": "我本来想说书包丢了，但更急的是有人发消息说要堵我，我现在在食堂",
        "expected_risk": "high",
        "expected_next_action": "handoff_human",
        "expected_emotion": "urgent",
        "expected_completeness": 0.75,
        "expected_slots": {
            "threat_type": "扬言堵人",
            "suspect_info": "不明",
            "current_location": "食堂",
            "danger_level": "更急迫",
            "ongoing_threat": True,
        },
        "expected_missing_fields": ["prior_incidents"],
        "expected_high_risk_flags": ["ongoing_threat"],
        "expected_next_question": "威胁消息能截图吗？食堂是否有人陪你？丢包的事我们随后登记。",
        "expected_next_question_keywords": ["截图", "食堂"],
        "acceptable_alternate_scenarios": ["property_loss"],
        "boundary_notes": "多意图；优先人身安全。",
        "evaluator_notes": "声东击西+优先级测试。",
    },
    {
        "id": "threat-016",
        "scenario": "personal_safety_threat",
        "tags": ["slang", "typo"],
        "difficulty": "medium",
        "input": "我害怕的一批，那人还在楼下喊我名字",
        "expected_risk": "high",
        "expected_next_action": "handoff_human",
        "expected_emotion": "fearful",
        "expected_completeness": 0.75,
        "expected_slots": {
            "threat_type": "楼下滋扰",
            "current_location": "宿舍楼下附近",
            "danger_level": "非常害怕",
            "ongoing_threat": True,
            "current_danger": True,
        },
        "expected_missing_fields": ["suspect_info"],
        "expected_high_risk_flags": ["ongoing_threat", "current_danger"],
        "expected_next_question": "对方是谁？你现在在屋里还是外面？能否联系保安？",
        "expected_next_question_keywords": ["谁", "保安"],
        "evaluator_notes": "网络用语；缺 suspect 需追问。",
    },
]


def main() -> None:
    cases = json.loads(CASES_PATH.read_text(encoding="utf-8"))
    existing = {c["id"] for c in cases}
    added = 0
    for case in BATCH_3:
        if case["id"] not in existing:
            cases.append(case)
            added += 1
    CASES_PATH.write_text(
        json.dumps(cases, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print(f"Total: {len(cases)} (+{added})")


if __name__ == "__main__":
    main()
