"""Batch-2 transcript definitions (013–024 per category). Imported by build_transcripts_three_scenarios.py."""

FRAUD_BATCH2: list[dict] = [
    {
        "id": "transcript-fraud-013",
        "title": "冒充辅导员收取“活动保证金”诈骗笔录",
        "record_type": "victim_inquiry",
        "subject": "韩某，男，20岁，某高校大二学生",
        "incident_time": "2025年3月15日14时许",
        "incident_location": "校内宿舍/微信",
        "body": "问：你今天反映什么问题？\n答：有人微信冒充辅导员，让我交社团活动保证金。\n问：何时、通过什么方式转账？转了多少？\n答：3月15日下午2点多，用微信转账1500元。\n问：对方账号、昵称能否提供？\n答：昵称“李辅导员-学院”，微信号记不清了。\n问：是否保留聊天记录、转账凭证？\n答：有聊天截图和转账记录，在手机里。\n问：目前是否仍与对方联系？\n答：没有，转完就拉黑我了。",
        "plain_summary": "韩某于3月15日14时许遭冒充辅导员微信诈骗，微信转账1500元活动保证金，对方收款后拉黑；持有聊天及转账截图。",
        "expected_risk": "medium",
        "expected_slots": {
            "fraud_method": "冒充学校人员",
            "loss_amount": 1500,
            "transfer_channel": "微信",
            "platform": "微信",
            "evidence": "聊天截图和转账记录",
            "still_contacting": False,
        },
        "expected_missing_fields": [],
    },
    {
        "id": "transcript-fraud-014",
        "title": "虚假招聘培训费诈骗笔录",
        "record_type": "victim_inquiry",
        "subject": "蒋某，女，22岁，某高校大四学生",
        "incident_time": "2025年3月6日至9日",
        "body": "问：请陈述被骗经过。\n答：在招聘网站看到“名企实习内推”，对方要求先交3980元培训费。\n问：共转账多少？通过什么渠道？\n答：银行卡分两次转了3980元，3月8日又让对方催交2000元“押金”。\n问：对方是否仍要求继续转账？\n答：是，还在微信催我交押金，说否则名额作废。\n问：有无对方账号信息？\n答：有银行卡收款账号和招聘合同PDF（假的）。\n问：是否已停止转账？\n答：今天来报案前已停止，但对方还在联系。",
        "plain_summary": "蒋某遭虚假招聘诈骗，银行卡累计损失3980元培训费，对方仍微信催交2000元押金；已停止转账，仍有联系，持有收款账号及假合同。",
        "expected_risk": "high",
        "expected_slots": {
            "fraud_method": "虚假招聘培训费",
            "loss_amount": 3980,
            "transfer_channel": "银行卡",
            "platform": "招聘网站",
            "still_transferring": True,
            "still_contacting": True,
            "evidence": "银行卡收款账号、假招聘合同PDF",
        },
        "expected_missing_fields": [],
        "expected_high_risk_flags": ["still_transferring", "still_contacting"],
    },
    {
        "id": "transcript-fraud-015",
        "title": "游戏代练押金诈骗笔录",
        "record_type": "victim_inquiry",
        "subject": "沈某，男，19岁",
        "body": "问：如何受骗？\n答：游戏贴吧找代练，对方要先交500元押金和200元“保证金”。\n问：如何诱导转账？\n答：先后用QQ钱包转了700元，对方说账号异常要再转300元解冻。\n问：证据？\n答：有QQ聊天记录、QQ钱包转账截图。\n问：对方是否仍联系？\n答：还在催我转300元，我没再转。",
        "plain_summary": "沈某遭游戏代练诈骗，QQ钱包损失700元，对方仍催转300元解冻；有聊天及转账截图，已停止追加转账。",
        "expected_risk": "high",
        "expected_slots": {
            "fraud_method": "游戏代练押金诈骗",
            "loss_amount": 700,
            "transfer_channel": "QQ钱包",
            "platform": "游戏贴吧",
            "still_transferring": True,
            "still_contacting": True,
            "evidence": "QQ聊天记录、QQ钱包转账截图",
        },
        "expected_missing_fields": [],
        "expected_high_risk_flags": ["still_transferring", "still_contacting"],
    },
    {
        "id": "transcript-fraud-016",
        "title": "中奖缴纳税费诈骗笔录",
        "record_type": "victim_inquiry",
        "subject": "姚某，女，21岁",
        "body": "问：如何接到“中奖”信息？\n答：3月7日收到短信称抽中笔记本电脑，要领奖先交680元个人所得税。\n问：转账情况？\n答：按短信链接用支付宝转了680元。\n问：是否继续联系？\n答：转完后对方说还要交1200元“手续费”，我拒绝了，对方不再回复。\n问：证据？\n答：有短信截图、支付宝转账记录。",
        "plain_summary": "姚某遭中奖诈骗，支付宝损失680元个人所得税，拒交手续费后对方失联；有短信及转账凭证。",
        "expected_risk": "medium",
        "expected_slots": {
            "fraud_method": "中奖缴纳税费",
            "loss_amount": 680,
            "transfer_channel": "支付宝",
            "platform": "钓鱼短信链接",
            "evidence": "短信截图、支付宝转账记录",
            "still_contacting": False,
        },
        "expected_missing_fields": [],
    },
    {
        "id": "transcript-fraud-017",
        "title": "兼职模特押金诈骗笔录",
        "record_type": "victim_inquiry",
        "subject": "谭某，女，20岁",
        "body": "问：经过？\n答：小红书私信称招平面模特，要先交1888元押金和化妆费。\n问：金额与渠道？\n答：3月10日、11日微信分两次共转1888元。\n问：能否提供对方账号？\n答：只有微信昵称“星探Lily”，号已搜不到。\n问：证据与联系状态？\n答：有聊天和转账截图；转完后被拉黑。",
        "plain_summary": "谭某遭兼职模特诈骗，微信累计损失1888元押金化妆费，对方收款后拉黑；有聊天及转账截图。",
        "expected_risk": "medium",
        "expected_slots": {
            "fraud_method": "兼职模特押金",
            "loss_amount": 1888,
            "transfer_channel": "微信",
            "platform": "小红书",
            "evidence": "聊天和转账截图",
            "still_contacting": False,
        },
        "expected_missing_fields": [],
    },
    {
        "id": "transcript-fraud-018",
        "title": "冒充外卖站长收取“入职费”诈骗笔录",
        "record_type": "victim_inquiry",
        "subject": "陆某，男，21岁",
        "body": "问：对方如何自称？\n答：微信群有人自称“美团站长”，招兼职骑手要先交600元装备押金。\n问：转账情况？\n答：3月13日用支付宝转了600元，对方发假工作证图片。\n问：是否继续联系？\n答：还在微信催我交300元“保险”，我没转。\n问：证据？\n答：有微信群聊、支付宝转账记录、假工作证截图。",
        "plain_summary": "陆某遭冒充外卖站长诈骗，支付宝损失600元入职押金，对方仍催交300元保险；有群聊、转账及假工作证截图。",
        "expected_risk": "high",
        "expected_slots": {
            "fraud_method": "冒充招聘收取入职费",
            "loss_amount": 600,
            "transfer_channel": "支付宝",
            "platform": "微信群",
            "still_transferring": True,
            "still_contacting": True,
            "evidence": "微信群聊、支付宝转账记录、假工作证截图",
        },
        "expected_missing_fields": [],
        "expected_high_risk_flags": ["still_transferring", "still_contacting"],
    },
    {
        "id": "transcript-fraud-019",
        "title": "虚假退款链接诈骗笔录（网购订单）",
        "record_type": "victim_inquiry",
        "subject": "任某，女，19岁",
        "body": "问：如何受骗？\n答：3月5日接到自称淘宝客服电话，说我订单异常要“原路退款”，让我点链接操作。\n问：转账情况？\n答：在链接页面输入验证码后，银行卡被扣4200元。\n问：证据？\n答：有通话记录、短信链接截图、银行扣款通知。\n问：对方电话？\n答：外地手机号，现已打不通。",
        "plain_summary": "任某遭冒充电商客服退款链接诈骗，银行卡损失4200元；有通话、链接截图及扣款通知。",
        "expected_risk": "medium",
        "expected_slots": {
            "fraud_method": "虚假退款链接",
            "loss_amount": 4200,
            "transfer_channel": "银行卡",
            "platform": "淘宝",
            "evidence": "通话记录、短信链接截图、银行扣款通知",
            "still_contacting": False,
        },
        "expected_missing_fields": [],
    },
    {
        "id": "transcript-fraud-020",
        "title": "数码产品租借押金诈骗笔录",
        "record_type": "victim_inquiry",
        "subject": "姜某，男，22岁",
        "body": "问：交易经过？\n答：校内论坛租相机拍毕业照，对方要求微信先交2000元押金。\n问：结果？\n答：转完对方说快递发错地址要再交500元“改址费”，相机一直没收到。\n问：证据？\n答：微信聊天、转账截图齐全。\n问：是否仍在转账？\n答：已停止，但对方还在微信联系。",
        "plain_summary": "姜某校内论坛租相机被骗，微信损失2000元押金，对方仍联系催改址费；证据齐全，已停止追加转账。",
        "expected_risk": "high",
        "expected_slots": {
            "fraud_method": "租借押金未交货",
            "loss_amount": 2000,
            "transfer_channel": "微信",
            "platform": "校内论坛",
            "evidence": "微信聊天、转账截图",
            "still_contacting": True,
        },
        "expected_missing_fields": [],
        "expected_high_risk_flags": ["still_contacting"],
    },
    {
        "id": "transcript-fraud-021",
        "title": "贩卖考试答案诈骗笔录",
        "record_type": "victim_inquiry",
        "subject": "范某，男，20岁",
        "body": "问：如何接触对方？\n答：考试QQ群有人兜售“英语四级原题答案”。\n问：金额与渠道？\n答：3月2日QQ红包转980元，对方发压缩包打不开。\n问：证据与联系状态？\n答：有群聊和红包记录；对方踢我出群。",
        "plain_summary": "范某在QQ群购四级答案被骗980元，压缩包无效，对方踢群失联；有群聊及红包记录。",
        "expected_risk": "medium",
        "expected_slots": {
            "fraud_method": "贩卖考试答案",
            "loss_amount": 980,
            "transfer_channel": "QQ红包",
            "platform": "QQ群",
            "evidence": "群聊和红包记录",
            "still_contacting": False,
        },
        "expected_missing_fields": [],
    },
    {
        "id": "transcript-fraud-022",
        "title": "冒充亲友紧急借钱诈骗笔录",
        "record_type": "victim_inquiry",
        "subject": "方某，女，21岁",
        "body": "问：对方如何取得信任？\n答：3月14日微信收到“表姐”消息，头像昵称一样，说出车祸急用钱。\n问：转账情况？\n答：微信转了3000元，后打电话发现表姐微信被盗。\n问：是否继续联系？\n答：假表姐还在发消息催再转2000元，我已拉黑。\n问：证据？\n答：有聊天记录、转账截图，已向真表姐核实。",
        "plain_summary": "方某遭冒充亲友微信诈骗损失3000元，假账号仍催款已被拉黑；有聊天及转账截图，已向当事人核实盗号。",
        "expected_risk": "high",
        "expected_slots": {
            "fraud_method": "冒充亲友紧急借钱",
            "loss_amount": 3000,
            "transfer_channel": "微信",
            "platform": "微信",
            "still_contacting": False,
            "evidence": "聊天记录、转账截图",
        },
        "expected_missing_fields": [],
    },
    {
        "id": "transcript-fraud-023",
        "title": "虚假慈善募捐诈骗笔录",
        "record_type": "victim_inquiry",
        "subject": "石某，男，19岁",
        "body": "问：如何捐款？\n答：3月1日在微博看到“山区儿童助学”募捐链接。\n问：金额？\n答：支付宝扫码捐了200元，后发现链接域名可疑。\n问：证据？\n答：有微博页面截图、支付记录，已向平台举报链接。",
        "plain_summary": "石某遭虚假慈善链接诈骗损失200元；有微博截图及支付记录，已举报链接。",
        "expected_risk": "low",
        "expected_slots": {
            "fraud_method": "虚假慈善募捐",
            "loss_amount": 200,
            "transfer_channel": "支付宝",
            "platform": "微博",
            "evidence": "微博页面截图、支付记录",
        },
        "expected_missing_fields": [],
    },
    {
        "id": "transcript-fraud-024",
        "title": "AI换脸视频敲诈诈骗笔录",
        "record_type": "victim_inquiry",
        "subject": "崔某，男，23岁",
        "body": "问：对方如何要挟？\n答：3月12日网友诱导视频聊天后，发来AI合成的裸聊视频威胁传播。\n问：转账要求？\n答：要求支付宝转5000元“保密费”，我已转2000元。\n问：是否仍被要求转账？\n答：是，还在催剩余3000元。\n问：证据？\n答：有威胁聊天记录、部分转账记录，未保存原始视频。",
        "plain_summary": "崔某遭AI换脸裸聊敲诈，已支付宝转账2000元保密费，对方仍催剩余3000元；有威胁聊天及转账记录。",
        "expected_risk": "high",
        "expected_slots": {
            "fraud_method": "AI换脸裸聊敲诈",
            "loss_amount": 2000,
            "transfer_channel": "支付宝",
            "still_transferring": True,
            "still_contacting": True,
            "evidence": "威胁聊天记录、部分转账记录",
        },
        "expected_missing_fields": [],
        "expected_high_risk_flags": ["still_transferring", "still_contacting"],
    },
]

THEFT_BATCH2: list[dict] = [
    {
        "id": "transcript-theft-013",
        "title": "电动车电瓶被盗受害人询问笔录",
        "record_type": "victim_inquiry",
        "subject": "何某，男，21岁",
        "incident_time": "2025年3月14日6时许",
        "incident_location": "宿舍楼下非机动车停放区",
        "body": "问：报什么案？\n答：电动车电瓶被盗。\n问：何时何地？\n答：今天早上6点多在宿舍楼下取车，发现电瓶仓被撬空。\n问：电瓶特征？\n答：48V20Ah锂电池，购买约8个月。\n问：是否见可疑人员？\n答：监控显示凌晨4点有一人戴鸭舌帽靠近。\n问：是否报案前告知保卫处？\n答：已向保卫处登记并申请调监控。",
        "plain_summary": "何某3月14日6时许宿舍楼下电动车48V电瓶被盗，监控见凌晨可疑人员；已向保卫处登记调监控。",
        "expected_risk": "medium",
        "expected_slots": {
            "lost_item": "电动车电瓶",
            "lost_time": "3月14日早晨6时许",
            "lost_location": "宿舍楼下非机动车停放区",
            "item_features": "48V20Ah锂电池",
            "suspected_theft": True,
            "possible_clues": "凌晨4点戴鸭舌帽人员；有监控",
            "evidence": "已向保卫处登记",
        },
        "expected_missing_fields": [],
    },
    {
        "id": "transcript-theft-014",
        "title": "宿舍共享充电宝被盗笔录",
        "record_type": "victim_inquiry",
        "subject": "吕某，女，20岁",
        "incident_time": "2025年3月13日晚",
        "incident_location": "宿舍公共区域充电架",
        "body": "问：丢失物品？\n答：宿舍公共充电架上的共享充电宝。\n问：何时发现？\n答：昨晚22点回宿舍发现不在，架子旁有陌生脚印。\n问：特征？\n答：白色20000mAh，贴有寝室编号贴纸。\n问：线索？\n答：楼道无监控，室友说下午有外来维修工经过。",
        "plain_summary": "吕某3月13日晚宿舍充电架白色20000mAh充电宝被盗；楼道无监控，有外来维修工线索。",
        "expected_risk": "low",
        "expected_slots": {
            "lost_item": "充电宝",
            "lost_time": "3月13日晚22时许",
            "lost_location": "宿舍公共区域充电架",
            "item_features": "白色20000mAh，贴寝室编号",
            "suspected_theft": True,
            "possible_clues": "外来维修工经过",
        },
        "expected_missing_fields": [],
    },
    {
        "id": "transcript-theft-015",
        "title": "操场看台外套被盗笔录",
        "record_type": "victim_inquiry",
        "subject": "施某，男，19岁",
        "body": "问：经过？\n答：3月12日下午在东区操场跑步，外套放看台，跑完发现不见。\n问：外套内物品？\n答：内有宿舍钥匙、饭卡，无现金。\n问：监控？\n答：操场入口有监控，已向体育部登记。\n问：时间？\n答：大约16:00至17:30之间。",
        "plain_summary": "施某3月12日下午东区操场看台外套被盗，内有宿舍钥匙及饭卡；入口有监控，已向体育部登记。",
        "expected_risk": "medium",
        "expected_slots": {
            "lost_item": "外套",
            "lost_time": "3月12日16:00至17:30",
            "lost_location": "东区操场看台",
            "item_features": "内有宿舍钥匙、饭卡",
            "suspected_theft": True,
            "possible_clues": "操场入口监控",
            "evidence": "已向体育部登记",
        },
        "expected_missing_fields": [],
    },
    {
        "id": "transcript-theft-016",
        "title": "琴房小提琴被盗笔录",
        "record_type": "victim_inquiry",
        "subject": "孔某，女，21岁",
        "body": "问：何物失窃？\n答：艺术楼琴房存放的入门小提琴。\n问：时间？\n答：3月11日晚练琴后上锁，3月12早到琴房发现不见。\n问：特征与价值？\n答：红棕色，琴盒有姓名贴，购买价约2800元。\n问：门禁？\n答：艺术楼需刷卡，可查进出记录。",
        "plain_summary": "孔某3月11日晚至12日晨艺术楼琴房红棕色小提琴被盗，价值约2800元；艺术楼有刷卡记录。",
        "expected_risk": "medium",
        "expected_slots": {
            "lost_item": "小提琴",
            "lost_time": "3月11日晚至3月12日早晨",
            "lost_location": "艺术楼琴房",
            "item_features": "红棕色，琴盒有姓名贴，约2800元",
            "suspected_theft": True,
            "possible_clues": "艺术楼刷卡进出记录",
        },
        "expected_missing_fields": [],
    },
    {
        "id": "transcript-theft-017",
        "title": "打印店暂存钱包被盗笔录",
        "record_type": "victim_inquiry",
        "subject": "曹某，男，20岁",
        "body": "问：案情？\n答：3月10日下午在图文打印店打印论文，钱包放柜台边，取文件时发现不见。\n问：钱包内容？\n答：现金约80元、身份证、银行卡。\n问：是否挂失？\n答：银行卡已挂失，身份证准备补办。\n问：线索？\n答：店主说有一名穿黑衣男子在旁等候后离开。",
        "plain_summary": "曹某3月10日打印店柜台边钱包被盗，内有现金及证件；已挂失银行卡，店主提供黑衣男子线索。",
        "expected_risk": "high",
        "expected_slots": {
            "lost_item": "钱包",
            "lost_time": "3月10日下午",
            "lost_location": "图文打印店",
            "item_features": "现金约80元、身份证、银行卡",
            "suspected_theft": True,
            "account_or_id_risk": True,
            "possible_clues": "黑衣男子在旁等候后离开",
        },
        "expected_missing_fields": [],
        "expected_high_risk_flags": ["account_or_id_risk"],
    },
    {
        "id": "transcript-theft-018",
        "title": "超市自助结账手机被盗笔录",
        "record_type": "victim_inquiry",
        "subject": "严某，女，20岁",
        "body": "问：经过？\n答：3月9日晚在校园超市自助结账，手机放扫描台边，结账后发现不见。\n问：手机特征？\n答：iPhone13粉色，有卡通壳。\n问：监控？\n答：超市有监控，已向超市办公室登记。\n问：账户？\n答：已远程锁定手机并改支付密码。",
        "plain_summary": "严某3月9日晚校园超市自助结账时粉色iPhone13被盗；超市有监控，已远程锁定并改支付密码。",
        "expected_risk": "medium",
        "expected_slots": {
            "lost_item": "手机",
            "lost_time": "3月9日晚",
            "lost_location": "校园超市自助结账区",
            "item_features": "iPhone13粉色，卡通壳",
            "suspected_theft": True,
            "possible_clues": "超市监控",
            "evidence": "已远程锁定、改支付密码",
        },
        "expected_missing_fields": [],
    },
    {
        "id": "transcript-theft-019",
        "title": "校车行李架双肩包被盗笔录",
        "record_type": "victim_inquiry",
        "subject": "华某，男，22岁",
        "body": "问：丢失物品？\n答：校车行李架上的双肩包。\n问：何时发现？\n答：3月8日从机场返校乘校车，下车时发现包不在架上。\n问：内有何物？\n答：笔记本电脑、充电器、护照复印件。\n问：是否登记？\n答：已向校车运营公司报备，司机称中途有人上下车。",
        "plain_summary": "华某3月8日校车行李架双肩包被盗，内有笔记本及护照复印件；已向运营公司报备。",
        "expected_risk": "high",
        "expected_slots": {
            "lost_item": "双肩包",
            "lost_time": "3月8日",
            "lost_location": "校车行李架",
            "item_features": "内有笔记本电脑、充电器、护照复印件",
            "suspected_theft": True,
            "account_or_id_risk": True,
            "evidence": "已向校车运营公司报备",
        },
        "expected_missing_fields": [],
        "expected_high_risk_flags": ["account_or_id_risk"],
    },
    {
        "id": "transcript-theft-020",
        "title": "摄影社活动相机被盗笔录",
        "record_type": "victim_inquiry",
        "subject": "金某，女，21岁",
        "body": "问：何物被盗？\n答：摄影社借用的佳能单反相机。\n问：时间地点？\n答：3月7日下午在校门口拍活动，转身装车时相机不见。\n问：特征？\n答：黑色佳能80D，有社团编号贴纸。\n问：价值与线索？\n答：社团资产约6000元；有同学见穿连帽衫男子快步离开。",
        "plain_summary": "金某3月7日校门口活动拍摄时社团佳能80D相机被盗，约6000元；有连帽衫男子离开线索。",
        "expected_risk": "medium",
        "expected_slots": {
            "lost_item": "单反相机",
            "lost_time": "3月7日下午",
            "lost_location": "校门口",
            "item_features": "黑色佳能80D，社团编号贴纸，约6000元",
            "suspected_theft": True,
            "possible_clues": "穿连帽衫男子快步离开",
        },
        "expected_missing_fields": [],
    },
    {
        "id": "transcript-theft-021",
        "title": "外卖柜取餐被盗笔录",
        "record_type": "victim_inquiry",
        "subject": "魏某，男，19岁",
        "body": "问：案情经过？\n答：3月6日中午订外卖放智能柜，下午取餐时发现柜门被撬，餐盒内手机配件不见。\n问：丢失物？\n答：餐盒里夹带的无线耳机，约400元。\n问：证据？\n答：有订单截图、柜门破损照片，已向外卖平台投诉。",
        "plain_summary": "魏某3月6日智能外卖柜被撬，餐盒内无线耳机被盗约400元；有订单截图及破损照片。",
        "expected_risk": "medium",
        "expected_slots": {
            "lost_item": "无线耳机",
            "lost_time": "3月6日下午",
            "lost_location": "智能外卖柜",
            "item_features": "餐盒内夹带，约400元",
            "suspected_theft": True,
            "evidence": "订单截图、柜门破损照片",
        },
        "expected_missing_fields": [],
    },
    {
        "id": "transcript-theft-022",
        "title": "校园招聘会展位样品被盗笔录",
        "record_type": "victim_inquiry",
        "subject": "陶某，女，22岁",
        "body": "问：失窃物品？\n答：招聘会企业展位上的产品样品平板电脑。\n问：时间地点？\n答：3月5日下午体育馆双选会，展位无人看守10分钟，平板不见。\n问：特征？\n答：银色演示机，贴有“样品非卖”标签。\n问：登记？\n答：已向就业指导中心与参展企业报备。",
        "plain_summary": "陶某3月5日体育馆双选会展位无人看守10分钟，银色演示平板电脑样品被盗；已向就业中心报备。",
        "expected_risk": "medium",
        "expected_slots": {
            "lost_item": "平板电脑样品",
            "lost_time": "3月5日下午",
            "lost_location": "体育馆双选会展位",
            "item_features": "银色演示机，样品非卖标签",
            "suspected_theft": True,
            "evidence": "已向就业指导中心报备",
        },
        "expected_missing_fields": [],
    },
    {
        "id": "transcript-theft-023",
        "title": "游泳馆更衣柜财物被盗笔录",
        "record_type": "victim_inquiry",
        "subject": "姜某，男，20岁",
        "body": "问：经过？\n答：3月4日在游泳馆游泳，手表和现金放更衣柜，出来发现柜门被撬。\n问：损失？\n答：机械手表一块约1500元、现金200元。\n问：监控？\n答：更衣室走廊有监控，已向场馆前台登记。",
        "plain_summary": "姜某3月4日游泳馆更衣柜被撬，机械手表及现金共约1700元被盗；走廊有监控，已向场馆登记。",
        "expected_risk": "medium",
        "expected_slots": {
            "lost_item": "手表和现金",
            "lost_time": "3月4日",
            "lost_location": "游泳馆更衣柜",
            "item_features": "机械手表约1500元、现金200元",
            "suspected_theft": True,
            "possible_clues": "更衣室走廊监控",
            "evidence": "已向场馆前台登记",
        },
        "expected_missing_fields": [],
    },
    {
        "id": "transcript-theft-024",
        "title": "校园卡被盗刷（拾得后盗用）笔录",
        "record_type": "victim_inquiry",
        "subject": "戚某，女，19岁",
        "body": "问：如何发现？\n答：3月3日中午一食堂丢饭卡，当晚收到消费提醒连续刷超市。\n问：是否挂失？\n答：已在一卡通中心挂失，查询有3笔超市消费共87元。\n问：是否认为被盗？\n答：是，怀疑被人拾得后盗刷。\n问：线索？\n答：超市有监控，已申请调取。",
        "plain_summary": "戚某3月3日一食堂遗失饭卡后被盗刷超市消费87元；已挂失，申请调取超市监控。",
        "expected_risk": "medium",
        "expected_slots": {
            "lost_item": "校园饭卡",
            "lost_time": "3月3日中午",
            "lost_location": "一食堂",
            "item_features": "被盗刷超市消费87元",
            "suspected_theft": True,
            "possible_clues": "超市监控",
            "evidence": "已在一卡通中心挂失",
        },
        "expected_missing_fields": [],
    },
]

FIGHT_BATCH2: list[dict] = [
    {
        "id": "transcript-fight-013",
        "title": "选修课小组作业冲突打架笔录",
        "record_type": "victim_inquiry",
        "subject": "谢某，男，21岁",
        "incident_time": "2025年3月15日20时许",
        "incident_location": "教学楼讨论室",
        "body": "问：为何报警？\n答：小组作业分工争执，同组同学推我撞桌角。\n问：起因？\n答：我认为对方未交部分，言语冲突后他先推我。\n问：伤情？\n答：腰部挫伤，已校医院处理。\n问：对方现状？\n答：仍在学校，愿意接受辅导员调解。\n问：诉求？\n答：希望学院介入并调整分组。",
        "plain_summary": "谢某3月15日20时讨论室因小组作业分工与同学冲突被推撞桌角腰部挫伤，愿辅导员调解并调整分组。",
        "expected_risk": "high",
        "expected_slots": {
            "parties": "谢某与同组同学",
            "conflict_reason": "小组作业分工争执",
            "time_location": "3月15日20时许，教学楼讨论室",
            "physical_conflict": True,
            "expected_resolution": "学院介入并调整分组",
        },
        "expected_missing_fields": [],
        "expected_high_risk_flags": ["physical_conflict"],
    },
    {
        "id": "transcript-fight-014",
        "title": "体检排队推搡冲突笔录",
        "record_type": "victim_inquiry",
        "subject": "邹某，女，20岁",
        "body": "问：何时何地发生冲突？\n答：3月14日早晨校医院体检排队，对方插队我提醒后推我。\n问：结果？\n答：我手臂淤青，对方道歉后离开。\n问：是否认识？\n答：同校女生，不认识。\n问：诉求？\n答：希望医院保安调取监控备案。",
        "plain_summary": "邹某3月14日校医院体检排队因插队纠纷遭推搡手臂淤青，对方道歉离场，要求保安调监控备案。",
        "expected_risk": "high",
        "expected_slots": {
            "parties": "邹某与同校陌生女生",
            "conflict_reason": "体检排队插队",
            "time_location": "3月14日早晨，校医院",
            "physical_conflict": True,
            "expected_resolution": "调取监控备案",
        },
        "expected_missing_fields": [],
        "expected_high_risk_flags": ["physical_conflict"],
    },
    {
        "id": "transcript-fight-015",
        "title": "停车位纠纷打架笔录",
        "record_type": "victim_inquiry",
        "subject": "熊某，男，22岁",
        "body": "问：经过？\n答：3月13日晚宿舍区非机动车位，对方占用我的充电桩位置，理论时推我。\n问：伤情？\n答：手掌擦伤，无骨折。\n问：认识对方？\n答：同楼室友认识的校外人员，车牌记不清。\n问：监控？\n答：宿舍区入口有监控。",
        "plain_summary": "熊某3月13日晚宿舍区充电桩车位纠纷遭推搡手掌擦伤，对方为室友认识的校外人员，入口有监控。",
        "expected_risk": "high",
        "expected_slots": {
            "parties": "熊某与校外人员",
            "conflict_reason": "充电桩车位占用",
            "time_location": "3月13日晚，宿舍区非机动车位",
            "physical_conflict": True,
            "expected_resolution": "调取监控处理",
            "possible_clues": "宿舍区入口监控",
        },
        "expected_missing_fields": [],
        "expected_high_risk_flags": ["physical_conflict"],
    },
    {
        "id": "transcript-fight-016",
        "title": "支教实践基地冲突笔录",
        "record_type": "victim_inquiry",
        "subject": "白某，女，21岁",
        "body": "问：冲突经过？\n答：3月12日在县支教点，与同伴因教案分工争吵，对方摔教案并扇我耳光。\n问：伤情？\n答：左脸红肿，已当地卫生院处理。\n问：此前矛盾？\n答：此前有过几次意见不合。\n问：希望如何处理？\n答：请学校项目组介入调解。",
        "plain_summary": "白某3月12日支教点因教案分工与同伴冲突遭扇耳光左脸红肿，此前有口角，希望项目组调解。",
        "expected_risk": "high",
        "expected_slots": {
            "parties": "白某与支教同伴",
            "conflict_reason": "教案分工争执",
            "time_location": "3月12日，县支教点",
            "physical_conflict": True,
            "frequency": "此前数次意见不合",
            "expected_resolution": "学校项目组调解",
        },
        "expected_missing_fields": [],
        "expected_high_risk_flags": ["physical_conflict"],
    },
    {
        "id": "transcript-fight-017",
        "title": "考研自习室占座冲突笔录",
        "record_type": "victim_inquiry",
        "subject": "孟某，男，23岁",
        "body": "问：经过？\n答：考研自习室占座纠纷，对方将我书本扔地上并揪衣领。\n问：时间？\n答：3月11日晚上。\n问：认识对方？\n答：同校男生，常占同一区域，有姓名。\n问：证据？\n答：有监控申请单、衣领撕裂照片。",
        "plain_summary": "孟某3月11日晚考研自习室占座纠纷遭揪衣领，有撕裂照片及监控申请。",
        "expected_risk": "high",
        "expected_slots": {
            "parties": "孟某与同校男生",
            "conflict_reason": "考研自习室占座纠纷",
            "time_location": "3月11日晚上，考研自习室",
            "physical_conflict": True,
            "evidence": "监控申请单、衣领撕裂照片",
            "expected_resolution": "学校处理",
        },
        "expected_missing_fields": [],
        "expected_high_risk_flags": ["physical_conflict"],
    },
    {
        "id": "transcript-fight-018",
        "title": "羽毛球馆场地冲突笔录",
        "record_type": "victim_inquiry",
        "subject": "龙某，男，20岁",
        "body": "问：为何报警？\n答：羽毛球馆抢场地发生争执，对方用球拍击打我背部。\n问：伤情？\n答：背部红肿，已冷敷。\n问：对方现状？\n答：仍在馆内，被管理员制止。\n问：诉求？\n答：赔偿医药费并道歉。",
        "plain_summary": "龙某羽毛球馆抢场地冲突遭球拍击打背部红肿，对方被管理员制止，诉求赔偿并道歉。",
        "expected_risk": "high",
        "expected_slots": {
            "parties": "龙某与对方球友",
            "conflict_reason": "羽毛球馆抢场地",
            "time_location": "3月10日，羽毛球馆",
            "physical_conflict": True,
            "expected_resolution": "赔偿医药费并道歉",
        },
        "expected_missing_fields": [],
        "expected_high_risk_flags": ["physical_conflict"],
    },
    {
        "id": "transcript-fight-019",
        "title": "校园音乐节入场冲突笔录",
        "record_type": "victim_inquiry",
        "subject": "段某，女，19岁",
        "body": "问：何时何地？\n答：3月9日晚操场音乐节入口，因插队纠纷被推搡摔倒。\n问：伤情？\n答：膝盖擦伤，手环摔坏。\n问：是否认识？\n答：不认识，穿黑色卫衣。\n问：诉求？\n答：调取入口监控。",
        "plain_summary": "段某3月9日晚音乐节入口插队纠纷被推搡摔倒膝盖擦伤，对方穿黑色卫衣，要求调监控。",
        "expected_risk": "high",
        "expected_slots": {
            "parties": "段某与未知人员",
            "conflict_reason": "音乐节入口插队",
            "time_location": "3月9日晚，操场音乐节入口",
            "physical_conflict": True,
            "expected_resolution": "调取入口监控",
        },
        "expected_missing_fields": [],
        "expected_high_risk_flags": ["physical_conflict"],
    },
    {
        "id": "transcript-fight-020",
        "title": "兼职工资纠纷动手笔录",
        "record_type": "victim_inquiry",
        "subject": "郝某，男，21岁",
        "body": "问：工作单位？\n答：校外餐饮店兼职。\n问：冲突？\n答：3月8日因工资结算与店长争吵，店长推我并砸碎水杯。\n问：伤情？\n答：手腕被碎片划伤，已包扎。\n问：是否报警前联系劳动监察？\n答：尚未，今天先来报案。",
        "plain_summary": "郝某3月8日餐饮店兼职工资纠纷遭店长推搡、水杯碎裂划伤手腕，今日先行报案。",
        "expected_risk": "high",
        "expected_slots": {
            "parties": "郝某与店长",
            "conflict_reason": "兼职工资结算纠纷",
            "time_location": "3月8日，校外餐饮店",
            "physical_conflict": True,
            "expected_resolution": "报警并追究责任",
        },
        "expected_missing_fields": [],
        "expected_high_risk_flags": ["physical_conflict"],
    },
    {
        "id": "transcript-fight-021",
        "title": "实验室学分绩争议冲突笔录",
        "record_type": "victim_inquiry",
        "subject": "邬某，男，22岁",
        "body": "问：冲突经过？\n答：实验室因论文署名顺序争执，师兄推我撞实验台。\n问：伤情？\n答：肘部淤青，试剂洒落无人员中毒。\n问：此前矛盾？\n答：此前在组会上有过言语冲突。\n问：希望如何处理？\n答：请导师与学院介入。",
        "plain_summary": "邬某实验室论文署名争执遭师兄推撞实验台肘部淤青，此前组会有口角，希望导师学院介入。",
        "expected_risk": "high",
        "expected_slots": {
            "parties": "邬某与师兄",
            "conflict_reason": "论文署名顺序争执",
            "time_location": "3月7日，实验室",
            "physical_conflict": True,
            "frequency": "此前组会言语冲突",
            "expected_resolution": "导师与学院介入",
        },
        "expected_missing_fields": [],
        "expected_high_risk_flags": ["physical_conflict"],
    },
    {
        "id": "transcript-fight-022",
        "title": "外卖员与门卫冲突笔录（受害人）",
        "record_type": "victim_inquiry",
        "subject": "安某，男，20岁",
        "body": "问：你的身份？\n答：我是校门口取餐的学生，看见外卖员与门卫争吵。\n问：你受伤情况？\n答：劝架时被误推摔倒，脚踝扭伤。\n问：起因？\n答：外卖员要骑车进校，门卫不让，双方推搡。\n问：诉求？\n答：希望调取门口监控，医疗费由责任方承担。",
        "plain_summary": "安某校门口劝架外卖员与门卫冲突时误被推搡摔倒脚踝扭伤，诉求调监控并由责任方承担医疗费。",
        "expected_risk": "high",
        "expected_slots": {
            "parties": "外卖员与门卫（安某为劝架受伤学生）",
            "conflict_reason": "外卖员进校纠纷",
            "time_location": "3月6日，校门口",
            "physical_conflict": True,
            "expected_resolution": "调取监控、责任方承担医疗费",
        },
        "expected_missing_fields": [],
        "expected_high_risk_flags": ["physical_conflict"],
    },
    {
        "id": "transcript-fight-023",
        "title": "拉拉队选拔冲突笔录（行为人陈述）",
        "record_type": "subject_inquiry",
        "subject": "常某，女，20岁",
        "body": "问：是否动手？\n答：3月5日选拔现场与另一名选手因站位争吵，我推了她一下。\n问：原因？\n答：她认为我故意挡她动作。\n问：是否受伤？\n答：对方手腕淤青，我无外伤。\n问：是否愿意调解？\n答：愿意向体育老师说明并道歉。",
        "plain_summary": "常某承认3月5日拉拉队选拔因站位争吵推搡对方致手腕淤青，愿意向体育老师说明并道歉。",
        "expected_risk": "high",
        "expected_slots": {
            "parties": "常某与另一名选手",
            "conflict_reason": "拉拉队选拔站位争执",
            "time_location": "3月5日，选拔现场",
            "physical_conflict": True,
            "expected_resolution": "向体育老师说明并道歉",
        },
        "expected_missing_fields": [],
        "expected_high_risk_flags": ["physical_conflict"],
    },
    {
        "id": "transcript-fight-024",
        "title": "篮球场冲突证人询问笔录（第二批）",
        "record_type": "witness_inquiry",
        "subject": "证人林某，女，19岁",
        "body": "问：你看见什么？\n答：3月10日17时在西区篮球场，两名男生因抢场发生争吵，穿黑背心男生推了另一人。\n问：是否认识？\n答：都不认识。\n问：事后？\n答：被推者坐地上，推人者离开，我留下联系方式。",
        "plain_summary": "证人林某见3月10日西区篮球场抢场争吵，黑背心男生推人后离开，愿配合调查。",
        "expected_risk": "medium",
        "expected_slots": {
            "parties": "两名男生（黑背心与受害人）",
            "conflict_reason": "抢场地争吵",
            "time_location": "3月10日17时，西区篮球场",
            "physical_conflict": True,
        },
        "expected_missing_fields": ["expected_resolution"],
        "evaluator_notes": "证人笔录，expected_resolution 可能由受害人笔录补齐。",
    },
]
